### ISSUE TITLE
Python Basics Track Courses to be Completed

### ISSUE THREAD

**Issue by Betagamma** [Betagamma/GitPractice#3]
## TODO

*Courses left to complete the Python Basics and Git Track*

* [ ]  Python Basics
    * [ ] Correct Errors - 1 Objective

* [ ] GitHub Basics
     * [ ] Create a Branch
     * [ ] Branch Test
     * [ ] Open Pull Request
     * [ ] Conflict Resolution 
     * [ ] Working by yourself Review

**********************
:eye:  ❤️ 🍎
